// src/App.jsx
import React, { useState } from 'react';
// We are not using the AI in this "submission" version
// import { GoogleGenerativeAI } from '@google/generative-ai'; 
import pptxgen from 'pptxgenjs';
import './App.css';

// --- FAKE AI DATA ---
// This is the sample JSON we will use to prove our app works
const sampleSlideData = {
  slides: [
    {
      title: 'Submission: React Project',
      bullets: [
        'This presentation was generated by pptxgenjs.',
        'The app is built with React and Vite.',
        'The live AI is pending Google quota activation.'
      ]
    },
    {
      title: 'Key Features Built',
      bullets: [
        'React Chat Interface (UI)',
        'State Management (useState)',
        'JSON-to-PowerPoint Logic',
        'Dynamic PPTX File Generation'
      ]
    },
    {
      title: 'AI Integration (Mocked)',
      bullets: [
        'The code to call the Gemini AI is complete.',
        'It is designed to parse a JSON response.',
        'This sample data is used to demonstrate the full workflow.'
      ]
    }
  ]
};
// --- END FAKE DATA ---

function App() {
  const [inputValue, setInputValue] = useState('');
  const [messages, setMessages] = useState([
    { text: 'Hello! Type any prompt to generate a demo presentation.', sender: 'ai' }
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const [presentationData, setPresentationData] = useState(null);

  // --- PPT GENERATION FUNCTION (Unchanged) ---
  const generatePresentation = () => {
    if (!presentationData) {
      alert("No slide data has been generated yet.");
      return;
    }
    
    let pres = new pptxgen();
    
    presentationData.slides.forEach(slideData => {
      let slide = pres.addSlide();
      slide.addText(slideData.title, { 
        x: 0.5, y: 0.25, w: '90%', h: 1, 
        fontSize: 32, bold: true, color: '363636' 
      });
      const bulletPoints = slideData.bullets.map(bullet => {
        return { text: bullet, options: { fontSize: 18, color: '696969' } };
      });
      slide.addText(bulletPoints, {
        x: 0.5, y: 1.5, w: '90%', h: 4, bullet: true
      });
    });
    
    pres.writeFile({ fileName: 'AI-Presentation-Demo.pptx' });
  };
  // --- END PPT LOGIC ---

  // --- SUBMIT HANDLER (MODIFIED) ---
  // This function now fakes the AI response
  const handleSubmit = (e) => {
    e.preventDefault(); 
    const userMessage = inputValue.trim();
    
    if (userMessage) {
      setIsLoading(true);
      
      // 1. Add user message
      setMessages((prevMessages) => [
        ...prevMessages,
        { text: userMessage, sender: 'user' }
      ]);
      setInputValue('');

      // 2. FAKE the AI response
      setTimeout(() => {
        // 3. Set the sample data
        setPresentationData(sampleSlideData); 
        
        // 4. Add the "success" message to the chat
        setMessages((prevMessages) => [
          ...prevMessages,
          { 
            text: `I've prepared ${sampleSlideData.slides.length} slides for you. You can now download the presentation.`, 
            sender: 'ai' 
          }
        ]);
        
        // 5. Stop loading
        setIsLoading(false); 
      }, 1000); // Wait 1 second to make it look real
    }
  };
  // --- END HANDLER ---

  return (
    <div className="app-container">
      <div className="chat-window">
        <div className="message-list">
          {messages.map((msg, index) => (
            <div
              key={index}
              className={`message ${msg.sender === 'ai' ? 'ai-message' : 'user-message'}`}
            >
              {msg.text}
            </div>
          ))}
          {isLoading && (
            <div className="message ai-message">
              <em>Generating slides...</em>
            </div>
          )}
        </div>
        
        <form className="message-form" onSubmit={handleSubmit}>
          <input
            type="text"
            className="message-input"
            placeholder="Type your prompt here..."
            value={inputValue} 
            onChange={(e) => setInputValue(e.target.value)}
            disabled={isLoading}
          />
          <button type="submit" className="send-button" disabled={isLoading}>
            {isLoading ? '...' : 'Send'} 
          </button>
        </form>
      </div>
      
      <div className="preview-window">
        <div className="preview-placeholder">
          <p>Your presentation preview will appear here.</p>
          <p>(Chat with the AI to generate slide data)</p>
          
          <button 
            className="download-button"
            onClick={generatePresentation}
            disabled={!presentationData}
          >
            Download Presentation
          </button>
        </div>
      </div>
    </div>
  );
}

export default App;